### PR TITLE
fix(default-theme): product variant change causes language change to default

### LINKED ISSUE #1717: [Bug] Change of product variant cause change domain url
### What happened?

change of product variant cause change domain url

### Steps To Reproduce

You need to have at lease two languages (two domains) on your sales channel.
Switch to the domain which is not a standard domain f.ex: `localhost/en-GB` 
Go to product detail page of product which have variants available
Change variant
Your domain will change to the standard
If you have also different currency, currency as is connected to domain will switch as well...

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Canary (generated by CLI)

### Which element is affected?

_No response_

### Environment

```markdown
- OS: Ubuntu latest
- Node: v10.24.1
- Shopware API: checked on v6.4.2.1 Stable Version and v6.3.5.1 Stable Versio
- Shopware PWA version: checked on 0.9.2 and 0.7.1
```

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by patzick**
## Changes

closes #1717 

The product variant didn't get the URL from the current domain.

### CODE REVIEW

File: packages/default-theme/src/components/SwProductDetails.vue [hunk 1]
```diff
@@ -117,14 +117,16 @@ export default {
...
         } else {
           // if no product was found - reset other options and try to find a first matching product
           const simpleOptionVariant = await findVariantForSelectedOptions({
             option: optionId,
           })
           if (simpleOptionVariant) {
-            root.$router.push(getProductUrl(simpleOptionVariant))
+            root.$router.push(
+              root.$routing.getUrl(getProductUrl(simpleOptionVariant))
+            )
```
Comment (mkucmus) [inline packages/default-theme/src/components/SwProductDetails.vue:129]: <3

**Review by mkucmus — APPROVED** [review]
xT5LMWOExnRmXt2vFS
