### PR TITLE
fix: default language settings

### LINKED ISSUE #1453: [BUG] Default language not correclty set
### Describe the bug

The default language is not correctly set if this is not english. This is happening in v.0.8.1, tested with a fresh instalation of shopware and shopware-pwa

### Steps to reproduce it

- Remove all domains if any and create only one like this
image

-  Update your domains using "yarn shopware-pwa domains"
- Start the shopware-pwa project, maybe clearing the cache is needed
- You will have german language for a second and then the language is set automatically to english, pay attention to the search field in the top bar.
- Setting defaultLanguageCode: 'de-DE' in config does not help.

### PR DESCRIPTION
**Pull request by patzick**
## Changes

closes #1453 
I'll do follow-up PR to master branch

### CODE REVIEW

File: packages/nuxt-module/plugins/i18n.js [hunk 1]
```diff
@@ -1,13 +1,18 @@
...
 Vue.use(VueI18n);
 
 export default ({ app }, inject) => {
+  const { sharedRef } = useSharedState(app);
+  const currentDomainData = sharedRef("sw-current-domain");
   // Set i18n instance on app
   // This way we can use it in middleware and pages asyncData/fetch
   const i18n = new VueI18n({
-    locale: "en-GB",
+    locale:
```
Comment (mkucmus) [inline packages/nuxt-module/plugins/i18n.js:13]: I won't miss it anymore in CR ! :)

Comment (patzick) [reply packages/nuxt-module/plugins/i18n.js:13]: It wouldn't work, either way, the other plugin is changing this value dynamically :)

**Review by mkucmus — APPROVED** [review]
