### PR TITLE
fix(nuxt-module): optional chaining to hasPrefixPath

### LINKED ISSUE #1750: [Bug] Cannot read property 'pathPrefix' of undefined
### What happened?

Running a fresh install of the latest (1.1.0) results in the following error:

`Cannot read property 'pathPrefix' of undefined` 

### Steps To Reproduce

1. Clean install of shopware-pwa using `npx @shopware-pwa/cli init`
2. Clean install of Shopware production template `v6.4.6.1` => shopware/production
3. fetch domains `npx @shopware-pwa/cli domains` => domains.json is created and set correctly
4. Run `npm run dev` or `yarn dev`
5. Open in browser, open console and the error appears

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest stable (generated by CLI)

### Which element is affected?

nuxt-module

### Environment

```markdown
- OS: macOs
- Node: 14
- Shopware API: 6.4.6.1
- Shopware PWA version: 1.1.0 (assuming we're talking about `@shopware-pwa/nuxt-module`)
```

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by mmeester**
closes #1750

### Checklist

- [x] I followed [contributing](https://github.com/DivanteLtd/shopware-pwa/blob/master/CONTRIBUTING.md) guidelines

### CODE REVIEW

File: packages/nuxt-module/plugins/domain.js [hunk 1]
```diff
@@ -140,7 +140,7 @@ export default async ({ app, route, req }, inject) => {
        */
 
       const hasPrefixPath = (domainConfig) => {
-        return domainConfig.pathPrefix !== "/";
+        return domainConfig?.pathPrefix !== "/";
```
Comment (mkucmus) [inline packages/nuxt-module/plugins/domain.js:143]: If domainConfig is `undefined` the result is `true`. maybe it would be safer if we return false if domainConfig is not set to have false instead of true in this case? WDYT

Comment (niklaswolf) [reply packages/nuxt-module/plugins/domain.js:145]: I don't know how this can happen, because every route should have the domainConfig now...
Give me some minutes to think this through

Comment (niklaswolf) [reply packages/nuxt-module/plugins/domain.js:145]: The error can come from two places essentially: 
1) https://github.com/vuestorefront/shopware-pwa/blob/258e6d51193ff2f8eae70b53af62d265fd3e4141/packages/nuxt-module/plugins/domain.js#L149 
2) https://github.com/vuestorefront/shopware-pwa/blob/258e6d51193ff2f8eae70b53af62d265fd3e4141/packages/nuxt-module/plugins/domain.js#L175 

One of those is undefined, so it would be a better fix in my opinion to add a condition to check the existance of `domainConfig` and `fromDomainConfig`:
1) https://github.com/vuestorefront/shopware-pwa/blob/258e6d51193ff2f8eae70b53af62d265fd3e4141/packages/nuxt-module/plugins/domain.js#L157
2) https://github.com/vuestorefront/shopware-pwa/blob/258e6d51193ff2f8eae70b53af62d265fd3e4141/packages/nuxt-module/plugins/domain.js#L181 

So it would be `domainConfig && !hasPrefixPath(domainConfig)` and `fromDomainConfig && !hasPrefixPath(fromDomainConfig)`

Additionally the optionalChaining can be added in `hasPrefixPath`. 
I'd rather not add the condition, because this is not what the function is about: it shouldn't return `false`, when `domainConfig` isn't set, this would be misleading. It should throw an exception instead.

**Review by niklaswolf — CHANGES_REQUESTED** [review]

File: packages/nuxt-module/plugins/domain.js (hunk 1 above)
Comment (mkucmus) [reply packages/nuxt-module/plugins/domain.js:145]: I found that the error probably comes from the point 2. (https://github.com/vuestorefront/shopware-pwa/blob/258e6d51193ff2f8eae70b53af62d265fd3e4141/packages/nuxt-module/plugins/domain.js#L175) mentioned by Niklas and it's because that on SSR there is now `from object set and `fromDomainConfig` is always `undefined`. @mmeester could you add another condition for that case?

**Review by niklaswolf — APPROVED** [review]

**Review by mkucmus — APPROVED** [review]
works fine!
